version: '3.8'

services:
  nestjs_starter_postgre:
    image: postgres:alpine
    container_name: nest_starter_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - nestjs_starter_postgres_data:/var/lib/postgresql/data
  nestjs_starter_redis:
    image: redis:alpine
    container_name: nestjs_starter_redis
    ports:
      - '6380:6379'
    volumes:
      - nestjs_starter_redis_data:/data

networks:
  default:
    name: nestjs_starter


volumes:
  nestjs_starter_postgres_data:
  nestjs_starter_redis_data: